#climate70.Rd
#country_iso.Rd
#drone_blades.Rd
#family_college.Rd
fish_oil_18.Rd
get_it_dunn_run.Rd
malaria.Rd
male_heights_fcid.Rd
nba_players_19.Rd
pew_energy_2018.Rd
photo_classify.Rd
playing_cards.Rd
simulated_dist.Rd
simulated_normal.Rd
simulated_scatter.Rd
smallpox.Rd
sp500_1950_2018.Rd
stocks_18.Rd
ucla_f18.Rd
ucla_textbooks_f18.Rd
